_core:
  default_config_hash: q2QxaHH2DKzN8zFKH4sBu5eWpPMNQERApyo7cDmngt4
path_type: path
path: /themes/custom/hyperluminal/favicon
tags:
  - '<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />'
  - '<link rel="icon" type="image/svg+xml" href="/favicon.svg" />'
  - '<link rel="shortcut icon" href="/favicon.ico" />'
  - '<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />'
  - '<link rel="manifest" href="/site.webmanifest" />'
cache_refresh_suffix: 1
show_missing: 0
remove_default: 1
